# Generated by Django 3.1.7 on 2021-03-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0002_auto_20210304_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldofstudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='field_of_studies',
            field=models.ManyToManyField(blank=True, to='Scholarship.Fieldofstudies'),
        ),
    ]
